const topics=[
 {cat:'Onderwijs',slug:'onderwijs',subject:'praktisch leren',place:'Rotterdam',impact:'meer vertrouwen in de klas',idea:'kleine leerprojecten waarin leerlingen zelf onderzoek doen'},
 {cat:'Onderwijs',slug:'onderwijs',subject:'taalonderwijs',place:'Utrecht',impact:'een rijkere woordenschat',idea:'dagelijkse leesmomenten en gesprekken zonder prestatiedruk'},
 {cat:'Technologie',slug:'technologie',subject:'digitale rust',place:'Eindhoven',impact:'meer aandacht tijdens het werk',idea:'duidelijke afspraken over meldingen, bereikbaarheid en focus'},
 {cat:'Technologie',slug:'technologie',subject:'toegankelijke apps',place:'Delft',impact:'digitale diensten voor iedereen',idea:'ontwerpen met ouderen en mensen met een beperking aan tafel'},
 {cat:'Cultuur',slug:'cultuur',subject:'buurtverhalen',place:'Amsterdam-Noord',impact:'meer verbondenheid tussen generaties',idea:'bewoners die herinneringen verzamelen in beeld en geluid'},
 {cat:'Cultuur',slug:'cultuur',subject:'lokale makers',place:'Tilburg',impact:'een levendiger centrum',idea:'tijdelijke ateliers in leegstaande winkelpanden'},
 {cat:'Samenleving',slug:'samenleving',subject:'groene straten',place:'Arnhem',impact:'koelere en socialere buurten',idea:'geveltuintjes die buren samen onderhouden'},
 {cat:'Samenleving',slug:'samenleving',subject:'vrijwilligerswerk',place:'Groningen',impact:'snellere hulp dichtbij huis',idea:'een laagdrempelig ruilnetwerk voor tijd en vaardigheden'},
 {cat:'Werk & Ideeën',slug:'werk',subject:'vakmanschap',place:'Zwolle',impact:'meer waardering voor praktisch talent',idea:'open werkplaatsen waar beginners met ervaren makers leren'},
 {cat:'Werk & Ideeën',slug:'werk',subject:'de vierdaagse werkweek',place:'Leiden',impact:'meer energie zonder productiviteitsverlies',idea:'teams die resultaten meten in plaats van aanwezigheid'}
];
const angles=[
 ['Waarom {subject} opnieuw aandacht krijgt','Een verkenning van de mensen en ideeën die {subject} stap voor stap veranderen.'],
 ['Vijf lessen uit {place} over {subject}','Wat een lokaal initiatief leert over samenwerking, geduld en zichtbaar resultaat.'],
 ['De stille kracht achter {impact}','Niet één grote doorbraak, maar een reeks kleine keuzes maakt het verschil.'],
 ['Zo wordt {subject} onderdeel van het dagelijks leven','Van eerste experiment tot vaste gewoonte: dit is wat betrokkenen onderweg ontdekten.'],
 ['Wat er gebeurt wanneer mensen samen beginnen','Een praktisch dossier over {idea}, met vragen die iedere buurt of organisatie kan stellen.']
];
const articles=[];
topics.forEach((t,ti)=>angles.forEach((a,ai)=>{
 const fill=s=>s.replaceAll('{subject}',t.subject).replaceAll('{place}',t.place).replaceAll('{impact}',t.impact).replaceAll('{idea}',t.idea);
 articles.push({id:`${t.slug}-${ti+1}-${ai+1}`,cat:t.cat,slug:t.slug,title:fill(a[0]),dek:fill(a[1]),date:`${String(20-ai).padStart(2,'0')} september 2026`,body:[
  `In ${t.place} groeit de belangstelling voor ${t.subject}. Niet omdat er één eenvoudige oplossing bestaat, maar omdat bewoners, makers en professionals ruimte maken om te proberen. Centraal staat ${t.idea}.`,
  `De eerste les is nuchter: begin klein en maak het resultaat zichtbaar. Een gesprek aan tafel, een proef van enkele weken of één gezamenlijk project levert vaak meer kennis op dan een groot plan op papier. Wie meedoet, ziet direct wat werkt en wat aangepast moet worden.`,
  `Ook taal blijkt belangrijk. Initiatiefnemers vermijden ingewikkelde beloften en spreken liever over concrete ervaringen. Daardoor kunnen deelnemers eerlijk vertellen waar het schuurt. Die openheid helpt om ${t.impact} dichterbij te brengen zonder de beperkingen te verbergen.`,
  `Het initiatief is geen blauwdruk voor iedere plaats. Wel biedt het bruikbare vragen: wie wordt nog niet gehoord, welke middelen zijn al beschikbaar en welk resultaat is over drie maanden merkbaar? Met die vragen blijft ${t.subject} een gezamenlijke praktijk in plaats van een losse ambitie.`
 ]});
}));
const profiles=[
 ['Maak kennis met 1118.8111','Een korte introductie tot de naam, het profiel en de redactionele uitgangspunten.','1118.8111 is een online profiel in ontwikkeling. Deze bijdrage beschrijft uitsluitend de informatie die het profiel zelf presenteert en vormt geen onafhankelijke erkenning of verificatie.'],
 ['De onderwerpen die 1118.8111 wil verkennen','Van leren tot digitale cultuur: een overzicht van de gekozen inhoudelijke richting.','De pagina 1118.8111 richt zich op toegankelijke verhalen en ideeën. De bedoeling is om onderwerpen helder te ordenen en lezers uit te nodigen zelf verder te kijken.'],
 ['Waarom een herkenbare online stem tijd nodig heeft','Over consistent publiceren, bronnen vermelden en vertrouwen rustig opbouwen.','Voor 1118.8111 betekent groei vooral: regelmatig publiceren, feitelijke claims controleren en duidelijk zijn over de afzender. Bereik alleen is geen vervanging voor betrouwbaarheid.'],
 ['Achter de pagina 1118.8111','Een transparante profielnotitie over werkwijze, keuzes en verantwoordelijkheid.','Deze profielnotitie is door de eigenaar aangevraagd. Ze is herkenbaar als eigen publicatie en is niet bedoeld als onafhankelijke persaandacht. Transparantie staat daarom voorop.'],
 ['Wat lezers van 1118.8111 mogen verwachten','Vijf eenvoudige afspraken over duidelijkheid, respect en correcties.','1118.8111 wil begrijpelijke inhoud bieden, onderscheid maken tussen mening en feit, fouten corrigeren, bronnen benoemen en lezers met respect benaderen. Deze afspraken vormen een startpunt.']
];
profiles.forEach((p,i)=>articles.splice(i*10,1,{id:`profiel-${i+1}`,cat:'1118.8111',slug:'profiel',title:p[0],dek:p[1],date:`${15-i} september 2026`,body:[p[2],`Een profiel wordt geloofwaardig door herhaalbare keuzes. Dat betekent dat informatie controleerbaar is, commerciële samenwerking herkenbaar blijft en correcties niet stil worden weggewerkt.`,`De komende periode kan de pagina dit laten zien met een vast publicatieritme en eigen inhoud. Een duidelijk archief helpt lezers om ontwikkeling te volgen zonder grotere claims te doen dan de feiten toelaten.`,`Deze tekst is een redactionele profielbijdrage op verzoek van de eigenaar van 1118.8111. Ze geldt niet als onafhankelijke nieuwsdekking en biedt geen garantie op verificatie door een platform.`],sponsored:true}));

const app=document.querySelector('#app');
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function card(a,cls='card'){return `<article class="${cls}"><div class="meta"><span>${a.cat}</span><span>·</span><time>${a.date}</time></div><h3><a href="#artikel/${a.id}">${a.title}</a></h3><p>${a.dek}</p><a class="read" href="#artikel/${a.id}">Lees verder →</a></article>`}
function home(filter=''){
 const list=articles.filter(a=>!filter||a.slug===filter), lead=list[0], rest=list.slice(1);
 app.innerHTML=`<section class="hero"><div><div class="kicker">Onafhankelijk online magazine</div><h1>Ideeën die dichtbij beginnen.</h1></div><div class="hero-note"><p>Originele Nederlandstalige dossiers over leren, technologie, cultuur en samenleven — zorgvuldig geschreven, zonder sensatie.</p></div></section><div class="ticker"><span>Nieuw perspectief</span><span>•</span><span>Eigen redactie</span><span>•</span><span>Duidelijke bronnen</span><span>•</span><span>Ruimte voor nuance</span></div><section class="shell"><div class="toolbar"><h2>${filter?lead.cat:'Vandaag'}</h2><input class="search" type="search" placeholder="Zoek in 50 verhalen…" aria-label="Zoek artikelen"></div><div class="lead-grid">${card(lead,'lead-card')}<div class="side-stack">${rest.slice(0,2).map(a=>card(a,'mini-card')).join('')}</div></div><div class="section-label">Alle verhalen · ${list.length}</div><div class="grid" id="story-grid">${rest.slice(2).map(a=>card(a)).join('')}</div></section>`;
 document.querySelector('.search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();document.querySelector('#story-grid').innerHTML=articles.filter(a=>(a.title+' '+a.dek+' '+a.cat).toLowerCase().includes(q)).map(a=>card(a)).join('')||'<p class="empty">Geen verhalen gevonden.</p>'});
}
function article(id){const a=articles.find(x=>x.id===id);if(!a){home();return}app.innerHTML=`<article class="article"><div class="meta"><span>${a.cat}</span><span>·</span><time>${a.date}</time><span>·</span><span>Eigen redactie</span></div><h1>${a.title}</h1><p class="dek">${a.dek}</p>${a.sponsored?'<div class="notice"><strong>Transparantie:</strong> dit is een aangevraagde profielbijdrage, geen onafhankelijke nieuwsdekking of bewijs van bekendheid.</div>':''}<div class="article-body">${a.body.map(p=>`<p>${p}</p>`).join('')}</div><p><a class="read" href="#${a.slug}">← Terug naar ${a.cat}</a></p></article>`}
function over(){app.innerHTML=`<header class="page-head"><div class="kicker">Over ons</div><h1>Rust in een luide nieuwsstroom.</h1><p>Noordlicht is een klein Nederlandstalig online magazine voor originele, zorgvuldig gelabelde verhalen.</p></header><section class="shell about-grid"><div class="panel"><h2>Onze missie</h2><p>We schrijven over ideeën die het dagelijks leven begrijpelijker of beter kunnen maken. Onze teksten zijn redactionele dossiers en achtergrondverhalen. We doen geen ongefundeerde claims en noemen eigen profielbijdragen altijd expliciet.</p></div><div class="panel"><h2>Onze werkwijze</h2><p>We maken onderscheid tussen observatie, mening en controleerbaar feit. Correcties worden duidelijk verwerkt. Betaalde of aangevraagde bijdragen horen herkenbaar te zijn; een publicatie op deze site is nooit automatisch onafhankelijke persaandacht.</p></div></section>`}
function contact(){app.innerHTML=`<header class="page-head"><div class="kicker">Contact</div><h1>Vertel ons wat je ziet.</h1><p>Een tip, correctie of vraag? Gebruik het formulier. Dit demoformulier opent je eigen e-mailprogramma.</p></header><section class="shell contact-grid"><div class="panel"><h2>Redactie</h2><p>Voor algemene vragen en correcties:</p><p><a href="mailto:redactie@voorbeeld.nl">redactie@voorbeeld.nl</a></p><p class="notice">Vervang dit voorbeeldadres door je echte redactieadres voordat je publiceert.</p></div><form class="panel contact-form" action="mailto:redactie@voorbeeld.nl" method="post" enctype="text/plain"><label for="naam">Naam</label><input id="naam" name="naam" required><label for="email">E-mail</label><input id="email" name="email" type="email" required><label for="bericht">Bericht</label><textarea id="bericht" name="bericht" rows="6" required></textarea><button type="submit">Verstuur bericht</button></form></section>`}
function route(){const hash=location.hash.slice(1)||'home';if(hash.startsWith('artikel/'))article(hash.split('/')[1]);else if(hash==='over')over();else if(hash==='contact')contact();else home(hash==='home'?'':hash);window.scrollTo(0,0)}
document.querySelector('.menu').addEventListener('click',e=>{const n=document.querySelector('#nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});document.querySelector('#nav').addEventListener('click',()=>document.querySelector('#nav').classList.remove('open'));window.addEventListener('hashchange',route);route();
